CREATE TABLE [dbo].[factApplication] (
    [ApplicationId]       INT            IDENTITY (1, 1) NOT NULL,
    [FName]               NVARCHAR (128) NOT NULL,
    [LName]               NVARCHAR (128) NOT NULL,
    [GTEmail]             NVARCHAR (256) NOT NULL,
    [RegEmail]            NVARCHAR (256) NULL,
    [Major]               NVARCHAR (256) NOT NULL,
    [CurrentStatus]       INT            NULL,
    [Reviewer]            INT            NULL,
    [GradYear]            INT            NOT NULL,
    [Position]            INT            NOT NULL,
    [TimeCommitmentValue] INT            NULL,
    [TCQ1]                INT            NOT NULL,
    [TCQ1A]               NVARCHAR (512) NOT NULL,
    [TCQ2]                INT            NOT NULL,
    [TCQ2A]               NVARCHAR (512) NOT NULL,
    [TCQ3]                INT            NOT NULL,
    [TCQ3A]               NVARCHAR (512) NOT NULL,
    [TCQ4]                INT            NOT NULL,
    [TCQ4A]               NVARCHAR (512) NOT NULL,
    [TCQ5]                INT            NULL,
    [TCQ5A]               NVARCHAR (512) NOT NULL,
    [Essay1Value]         INT            NULL,
    [Essay1Q]             INT            NOT NULL,
    [Essay1A]             NVARCHAR (MAX) NOT NULL,
    [Essay2Value]         INT            NULL,
    [Essay2Q]             INT            NOT NULL,
    [Essay2A]             NVARCHAR (MAX) NOT NULL,
    [Essay3Value]         INT            NULL,
    [Essay3Q]             INT            NOT NULL,
    [Essay3A]             NVARCHAR (MAX) NOT NULL,
    [Linkedin]            NVARCHAR (256) NULL,
    [Portfolio]           NVARCHAR (256) NULL,
    CONSTRAINT [PK_Application] PRIMARY KEY CLUSTERED ([ApplicationId] ASC)
);

